const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function harness(){let now=0,id=0;const timers=new Map(),elements=new Map();function el(){return {innerHTML:'',textContent:'',className:'',classList:{add(){},remove(){}},append(){},insertAdjacentHTML(){},querySelector(){return el()},remove(){},pause(){},load(){},removeAttribute(){}};}const doc={body:el(),querySelector:s=>{if(!elements.has(s))elements.set(s,el());return elements.get(s)},createElement:el};let keyboard;const ctx={document:doc,AbortController,console,AudioContext:class{currentTime=0;resume(){}createOscillator(){return {connect(){},frequency:{},start(){},stop(){}}}createGain(){return {connect(){},gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}}}}},setTimeout:(f,ms)=>{timers.set(++id,{f,at:now+ms});return id},clearTimeout:i=>timers.delete(i)};ctx.window=ctx;ctx.addEventListener=(_,f)=>keyboard=f;vm.createContext(ctx);for(const f of ['config.js','rules.js','game.js'])vm.runInContext(fs.readFileSync('src/'+f,'utf8'),ctx);async function flush(){for(let i=0;i<12;i++)await Promise.resolve();}async function step(){await flush();const next=[...timers].sort((a,b)=>a[1].at-b[1].at)[0];assert.ok(next,'expected timer');timers.delete(next[0]);now=next[1].at;next[1].f();await flush();}return {ctx,async key(code){keyboard({code,preventDefault(){}});await flush()},async until(pred){for(let i=0;i<500;i++){if(pred(ctx.gameStatus()))return;await step();}throw Error('condition not reached')},step,get now(){return now}};}
async function reach(h,phase){await h.until(s=>s.phase===phase&&s.waiting);}
async function questions(h,choices){await h.key('Space');for(let i=0;i<3;i++){await reach(h,'P'+(i+5));if(choices[i])await h.key(choices[i]);else{await h.step();await h.step();}}}
test('all eight combinations: only three lefts pass',()=>{const {passes}=require('../src/rules.js');for(let mask=0;mask<8;mask++)assert.equal(passes([0,1,2].map(i=>mask&(1<<i)?'right':'left')),mask===0);});
test('C: three left choices and final right, then automatic reset',async()=>{const h=harness();await questions(h,['ArrowLeft','ArrowLeft','ArrowLeft']);await reach(h,'P9C');await h.key('ArrowRight');await h.until(s=>s.ending==='C');await h.step();assert.equal(h.ctx.gameStatus().phase,'P0');});
test('A2: unanswered questions count as left; final timeout abandons',async()=>{const h=harness();await questions(h,[null,null,null]);await reach(h,'P9C');assert.deepEqual(Array.from(h.ctx.gameStatus().answers),['left','left','left']);await h.until(s=>s.ending==='A2');});
test('A1: rejection ignores left/right and times out after 5 seconds',async()=>{const h=harness();await questions(h,['ArrowRight','ArrowLeft','ArrowLeft']);await reach(h,'P9R');const t=h.now;await h.key('ArrowLeft');assert.equal(h.ctx.gameStatus().waiting,true);await h.step();assert.equal(h.now-t,5000);await h.until(s=>s.ending==='A1');});
test('B: any of three buttons confirms each term',async()=>{const h=harness();await questions(h,['ArrowRight','ArrowRight','ArrowRight']);await reach(h,'P9R');await h.key('Space');for(const key of ['ArrowLeft','Space','ArrowRight']){await reach(h,'P10B');await h.key(key);}await h.until(s=>s.ending==='B');});
test('A3: hesitation repeats after continue, third key ignored, timeout terminates',async()=>{const h=harness();await questions(h,['ArrowRight','ArrowLeft','ArrowLeft']);await reach(h,'P9R');await h.key('Space');await reach(h,'P10B');const t=h.now;await h.step();assert.equal(h.now-t,5000);await reach(h,'P10B');await h.key('Space');assert.equal(h.ctx.gameStatus().waiting,true);await h.key('ArrowRight');await reach(h,'P10B');await h.step();await reach(h,'P10B');await h.until(s=>s.ending==='A3');});
test('F1 cancels opening; repeated start input cannot skip intro',async()=>{const h=harness();await h.key('Space');await h.key('ArrowRight');assert.equal(h.ctx.gameStatus().phase,'P1');await h.key('F1');assert.equal(h.ctx.gameStatus().phase,'P0');await h.key('Space');await reach(h,'P5');assert.equal(h.ctx.gameStatus().answers.length,0);await h.key('F1');assert.equal(h.ctx.gameStatus().waiting,false);});
