/* 独立的演出流程；将来硬件只需发送相同键盘事件。 */
const C=window.GAME_CONFIG,stage=document.querySelector('#stage'),sub=document.querySelector('#subtitle');
let run,accept=null,answers=[],ending=null,phase='P0',hooks=0,hesitate=false,startKey='third',devMuted=false,currentBeat='P0',session=0;
const KNOWN_BEATS=new Set(['P0','P1','P2','P3','P4','P5','P6','P7','P8','P9C','P9R','P10B','P11.A1','P11.A2','P11.A3','B','C','P12']);
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function live(sid){return sid===session&&run&&!run.signal.aborted;}
function guard(sid){if(!live(sid))throw new Error('reset');}
function settleOnce(){let done=false;return fn=>{if(done)return;done=true;fn();};}
function wait(ms,sid){const signal=run.signal;return new Promise((resolve,reject)=>{if(!live(sid))return reject(new Error('reset'));const once=settleOnce();const finish=fn=>once(()=>{clearTimeout(id);signal.removeEventListener('abort',onAbort);fn();});const onAbort=()=>finish(()=>reject(new Error('reset')));const id=setTimeout(()=>{if(!live(sid))return finish(()=>reject(new Error('reset')));finish(resolve);},ms*C.speed);signal.addEventListener('abort',onAbort,{once:true});});}
function type(el,text){el.innerHTML=[...text].map((c,i)=>`<span class="char" style="animation-delay:${i*C.typeMs*C.speed}ms">${esc(c)}</span>`).join('');}
function view(html,id){phase=id||phase;if(id)currentBeat=id;document.querySelector('#phase').textContent=phase==='P0'?'SYSTEM STANDBY':`SESSION  /  ${phase}`;stage.innerHTML=html;sub.textContent='';}
function keys(active=[]){document.querySelector('#keys').innerHTML=[['left','←','左键'],['right','→','右键'],['third','␣','白色按钮']].map(([id,k,l])=>`<span class="key ${id==='right'?'warm':''} ${active.includes(id)?'on':''}" data-key="${id}"><b>${k}</b>${l}</span>`).join('');}
async function audio(path,fallback,sid){if(devMuted||!path)return wait(fallback,sid);const signal=run.signal;if(!live(sid))throw new Error('reset');await new Promise((resolve,reject)=>{const a=new Audio(path);const once=settleOnce();let timer;const finish=fn=>once(()=>{clearTimeout(timer);a.pause();signal.removeEventListener('abort',onAbort);fn();});const onAbort=()=>finish(()=>reject(new Error('reset')));signal.addEventListener('abort',onAbort,{once:true});a.onended=()=>{if(!live(sid))return finish(()=>reject(new Error('reset')));finish(resolve);};a.onerror=()=>{timer=setTimeout(()=>{if(!live(sid))return finish(()=>reject(new Error('reset')));finish(resolve);},fallback*C.speed);};a.play().catch(()=>a.onerror());});}
async function say(id,text,ms,sid){guard(sid);type(sub,text);await audio(C.assets.voice[id],ms??Math.max(1500,text.length*155),sid);guard(sid);}
function sfx(id,sid){if(!live(sid)||devMuted)return;const path=C.assets.sfx[id];if(path){const a=new Audio(path);const stop=()=>a.pause();run.signal.addEventListener('abort',stop,{once:true});a.onended=()=>run.signal.removeEventListener('abort',stop);a.play().catch(()=>{});return;}const ctx=window.fx||(window.fx=new AudioContext());ctx.resume();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.value={ding:1100,thud:65,tick:700,beep:900,ready:1400}[id]||800;gain.gain.setValueAtTime(.025,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.18);osc.start();osc.stop(ctx.currentTime+.2);}
function choice(valid,timeout,promptAt,prompt,sid){keys(valid);return new Promise((resolve,reject)=>{const signal=run.signal;if(!live(sid))return reject(new Error('reset'));const once=settleOnce();let timer,reminder,promptAudio;const clear=()=>{clearTimeout(timer);clearTimeout(reminder);promptAudio?.pause();accept=null;signal.removeEventListener('abort',onAbort);keys();};const finish=fn=>once(()=>{clear();fn();});const onAbort=()=>finish(()=>reject(new Error('reset')));accept=key=>{if(!live(sid))return;if(valid.includes(key))finish(()=>resolve(key));};signal.addEventListener('abort',onAbort,{once:true});if(timeout)timer=setTimeout(()=>{if(!live(sid))return finish(()=>reject(new Error('reset')));finish(()=>resolve('timeout'));},timeout*C.speed);if(promptAt)reminder=setTimeout(()=>{if(!live(sid))return;type(sub,prompt);const path=C.assets.voice[phase+'.prompt'];if(path&&!devMuted){promptAudio=new Audio(path);promptAudio.play().catch(()=>{});}},promptAt*C.speed);});}
const orb='<div class="orb"></div>';
function heading(k,t){return `<div class="eyebrow">${k}</div><h1>${t}</h1>`;}
function cards(title,left,right){return heading('DECISION SIMULATION',title)+`<div class="choices"><div class="card"><label>← &nbsp; 系统方案</label><h2>${left[0]}</h2>${left.slice(1).map(t=>`<p>${t}</p>`).join('')}</div><div class="card warm"><label>→ &nbsp; 自主选择</label><h2>${right[0]}</h2>${right.slice(1).map(t=>`<p>${t}</p>`).join('')}</div></div><p class="prompt">请选择</p>`;}
function showStandby(){view('<div class="eyebrow">自主决策能力评估 / 07</div>'+orb+'<h1 class="standby">按任意按钮开始</h1><p class="prompt">请先就座</p>','P0');keys(['left','right','third']);}
function clearChrome(){accept=null;document.body.className='';stage.className='';sub.className='';const v=document.querySelector('#video');v.pause();v.removeAttribute('src');v.load();document.querySelector('#signature').textContent='评估室 07';}
async function sceneP1(sid){keys(['left','right','third']);document.querySelector(`[data-key="${startKey}"]`)?.classList.add('flash');view(orb.replace('orb','orb frozen'),'P1');await wait(200,sid);guard(sid);keys();await wait(300,sid);guard(sid);stage.insertAdjacentHTML('beforeend','<div class="scan"></div>');await wait(1000,sid);guard(sid);view(heading('APPLICANT DETECTED','检测到申请人。'));await say('p1.detect','检测到申请人。',null,sid);}
async function sceneP2(sid){const intro=['2078年。','现在，你的人生已无需由你决定。','起初，人工智能只计算风险。后来，它分配工作、住房与伴侣。','它很少出错。于是，全人类签署授权：交出选择权。','从此，你无须犹豫，无须承担选错的后果。','“自主决定”，成了一项需要申请的权限。','欢迎来到——人类自主权恢复中心。'];
 const video=document.querySelector('#video');if(C.assets.video.intro){video.src=C.assets.video.intro;video.loop=true;video.play().catch(()=>{});}
 for(let i=0;i<intro.length;i++){guard(sid);view(`<div class="eyebrow">ARCHIVE / ${String(i+1).padStart(2,'0')}</div><h2 id="narrative" style="max-width:860px"></h2>`,'P2');type(document.querySelector('#narrative'),intro[i]);await wait(C.introDurations[i],sid);}video.pause();video.removeAttribute('src');video.load();await say('p2.welcome','用户xxxxx你好，你的自主权恢复申请，已获准进入测试阶段。',null,sid);}
async function sceneP3(sid){view(heading('DECISION HISTORY','过去 18 年，系统已代替你完成：')+'<div class="data"></div>','P3');for(const text of ['教育路径选择','职业选择','居住地选择','健康决策','社交关系优化','伴侣匹配','消费选择','累计替代决策：11,204 次']){guard(sid);const p=document.createElement('p');if(text.startsWith('累计'))p.className='total';document.querySelector('.data').append(p);sfx('beep',sid);type(p,text);await wait(650,sid);}await say('p3.count','十八年间，系统为你完成 11,204 次决定。',null,sid);await wait(1000,sid);await say('p3.perfect','它们从未出错。',null,sid);}
async function sceneP4(sid){view(heading('ASSESSMENT PROTOCOL','恢复自主权前，须完成三项决策模拟')+'<p>工作　 /　 爱情　 /　 记忆</p>','P4');await say('p4.meaning','本次考核将以三项决策模拟，评估你的自主决策能力：如何生存，与谁亲密，以及如何面对无法删除的记忆。',null,sid);await wait(1000,sid);await say('p4.simulations','现在，测试开始。',null,sid);await wait(1000,sid);await say('p4.record','没有标准答案。你的每一次选择，都会被记录。',null,sid);}
async function sceneP8(sid){view(heading('PROCESSING', '正在评估自主决策能力')+orb,'P8');await wait(2000,sid);guard(sid);if(GameRules.passes(answers))await passed(sid);else await rejected(sid);}
async function question(i,sid){const names=['工作','爱情','记忆'],left=[['不喜欢的工作','收入较高','成功概率 94%'],['匹配度 91%','预计持续 27 年'],['删除','预计使未来情绪稳定度提升 22%']],right=[['真正喜欢的工作','收入较低','成功概率 31%'],['匹配度 52%','预计持续 4 年','但你爱这个人'],['保留']];const id=`P${5+i}`;
 if(i===2){view(heading('MEMORY DETECTED','系统检测到一段高痛苦记忆')+'<p>（已模糊化处理）</p>',id);await wait(2600,sid);guard(sid);document.body.classList.add('black');await wait(1000,sid);guard(sid);document.body.classList.remove('black');}
 view(cards(`第${['一','二','三'][i]}题：${names[i]}`,left[i],right[i]),id);await say(`${id}.intro`,`第${['一','二','三'][i]}个问题：${names[i]}。`,null,sid);await wait(700,sid);await say(`${id}.choose`,'请选择。',1000,sid);let a=await choice(['left','right'],C.questionTimeout,C.questionPrompt,'系统在等待。',sid);guard(sid);if(a==='timeout'){a='right';await say(`${id}.auto`,'未收到选择。系统将按更有人情味的方案记录。',null,sid);}answers.push(a);view(heading('RESPONSE RECORDED','已记录。'),id);
 if(i===0){sfx(a==='left'?'ding':'thud',sid);await say(`${id}.${a}`,a==='left'?'已记录。该选择预计使长期生活稳定度提升 17.4%。':'已记录。根据历史样本，该选择产生长期后悔的概率为 63%。',null,sid);}
 if(i===1){await say(`${id}.record`,'已记录。',1000,sid);if(a==='left'){await wait(2000,sid);await say(`${id}.left`,'该匹配由系统预先安排。',null,sid);}else{sub.textContent='';await wait(3000,sid);}}
 if(i===2){await say(`${id}.record`,'已记录。',1000,sid);if(a==='right'){await wait(1000,sid);await say(`${id}.right`,'这段记忆，将在未来十二个月里更频繁地回来。',null,sid);}}}
function result(){view(heading('AUTONOMY RESTORED','自主权已恢复')+'<p class="result">未来结果：无法预测</p>');}
async function costs(prefix,sid){await say(prefix+'.errors','系统将不再替你避免所有错误。',null,sid);await wait(1000,sid);await say(prefix+'.pain','系统将不再替你删除所有痛苦。',null,sid);await wait(1000,sid);await say(prefix+'.optimal','系统将不再替你保证最优人生。',null,sid);await wait(5000,sid);}
async function passed(sid){phase='P9C';currentBeat='P9C';result();await say('c.confirm','已确认。',null,sid);await say('c.restored','自主权恢复完成。',null,sid);await wait(1000,sid);await costs('c',sid);view(cards('最后一次确认：是否仍要恢复自主权？',['放弃'],['恢复']),'P9C');await say('c.ask','最后一次询问。是否仍要恢复自主权？',null,sid);const a=await choice(['left','right'],C.finalTimeout,C.finalPrompt,'系统在等待确认。',sid);guard(sid);if(a==='right')await endingC(sid);else{if(a==='timeout')await say('c.timeout','未收到确认。系统将维持现状。',null,sid);await say('a2.confirm','已确认。',null,sid);await say('a2.stop','恢复程序已终止。',null,sid);await endingA('A2',sid);}}
async function rejected(sid){view(heading('ASSESSMENT REPORT / 07','申请已驳回')+'<table class="report"><tr><td>自主决策风险</td><td>高</td></tr><tr><td>后悔耐受度</td><td>低</td></tr><tr><td>情绪波动</td><td>高</td></tr><tr><td>决策效率</td><td>43%</td></tr></table>','P9R');await say('r.sorry','很遗憾。',null,sid);await say('r.unfit','你目前并不适合恢复自主决策权。',null,sid);await wait(1000,sid);await say('r.common','这种情况很常见。98.6% 的申请人最终得到相同结果。',null,sid);await wait(1000,sid);await say('r.reject','系统将驳回你对自主决策权的申请。',null,sid);await wait(1000,sid);await say('r.override','若您执意收回自由决策权，您可以按下白色按钮。',null,sid);view('<div class="fade"><h2>申请已驳回</h2></div><h1>请保持原位</h1><span style="position:absolute;right:5vw;bottom:160px" class="tiny">强制收回决策权（白色按钮 · 空格）</span>');sfx('ready',sid);const a=await choice(['third'],C.rejectionTimeout,null,null,sid);guard(sid);if(a==='third')await contract(sid);else{await say('r.noRequest','未收到强制收回请求。',null,sid);await say('r.maintain','系统将维持驳回结果。',null,sid);await endingA('A1',sid);}}
const terms=['你可能会选择错误的人。','你可能会错过更好的机会。','你可能会后悔。'];
function contractView(n){view('<div class="eyebrow">RESTORATION / CONSENT</div><h2>如仍要恢复自主权，请确认你接受以下全部后果：</h2><div class="contract">'+terms.slice(0,n+1).map((t,i)=>`<div class="check"><span>${i<n?'✓':'□'}</span>${t}</div>`).join('')+'</div><p class="prompt">按任意一颗按钮确认</p>','P10B');}
async function endingBCore(sid){await say('b.promise','我无法保证你会过得更好。',null,sid);document.body.classList.add('minimal');view(orb);await wait(3000,sid);guard(sid);document.body.classList.remove('minimal');phase='B';currentBeat='B';result();await say('b.confirm','已确认。',null,sid);await wait(1000,sid);await costs('b',sid);await say('b.luck','祝你好运。',null,sid);await finish('B',sid);}
async function contract(sid){if(hooks>=3)return endingBCore(sid);view(heading('OVERRIDE REQUEST','检测到强制收回请求。'),'P10B');await say('b.detect','检测到强制收回请求。',null,sid);await wait(1000,sid);await say('b.risk','恢复自主权将显著增加人生风险。',null,sid);let n=hooks;while(n<3){guard(sid);contractView(n);await say(`b.term${n+1}`,terms[n],null,sid);await say('b.accept','若接受，请按任意按钮。',null,sid);const waitMs=hesitate?1:C.hesitationTimeout;hesitate=false;const a=await choice(['left','right','third'],waitMs,null,null,sid);guard(sid);if(a==='timeout'){stage.insertAdjacentHTML('beforeend','<div class="overlay"><div class="eyebrow">CONFIRMATION REQUIRED</div><p>系统检测到您的犹豫。</p><h2>是否还想要拥有自主决策权？</h2><div class="choices"><div class="card"><h2>← 否 · 放弃</h2></div><div class="card warm"><h2>→ 是 · 继续</h2></div></div></div>');await say('b.hesitate','系统检测到您的犹豫。',null,sid);await wait(800,sid);await say('b.want','是否还想要拥有自主决策权？',null,sid);const answer=await choice(['left','right'],C.hesitationAnswerTimeout,null,null,sid);guard(sid);if(answer==='right'){await say('b.continue','请继续。',null,sid);continue;}if(answer==='timeout'){await say('a3.noAnswer','未收到应答。',null,sid);await wait(800,sid);}stage.querySelector('.overlay')?.remove();await say('a3.confirm','已确认。',null,sid);await wait(800,sid);await say('a3.hesitation','你的犹豫，已经替你回答了这个问题。',null,sid);await wait(800,sid);view(heading('APPLICATION TERMINATED','自主决策权申请：已终止'));await say('a3.stop','自主决策权申请已终止。',null,sid);return endingA('A3',sid);}sfx('tick',sid);n++;hooks=n;contractView(n);await wait(300,sid);}
 await endingBCore(sid);}
async function endingC(sid){result();await say('c.luck','祝你好运。',null,sid);await wait(1000,sid);await say('c.leave','你可以离开了。',null,sid);await wait(1000,sid);await say('c.rational','系统相信你今后也能做出理性选择。',null,sid);await finish('C',sid);}
async function endingA(entry,sid){ending=entry;currentBeat='P11.'+entry;document.body.classList.add('guidance');document.querySelector('#signature').textContent='人生指导系统：运行中';view(heading('YOUR PERSONAL GUIDANCE','人生指导系统：运行中')+'<div class="timeline"></div>','P11');await say('a.thanks','感谢你的信任。',null,sid);await say('a.next','你的下一项重大人生决定将在四年后执行。',null,sid);const lines=['四年后 · 工作：辞去现在的工作，转入系统为你保留的岗位（长期稳定度预计提升 17.4%）。','六年后 · 婚姻：对象由系统配定（匹配度 98.6%）。你将在婚礼前三个月第一次见到对方。','十一年后 · 记忆：进行一次记忆清理。内容你不需要知道。'];for(const text of lines){guard(sid);const p=document.createElement('p');document.querySelector('.timeline').append(p);type(p,text);await wait(Math.max(4000,text.length*130),sid);}await say('a.reassure','不过，请放心。',null,sid);await wait(1000,sid);await say('a.decided','我已经替你决定好了。',null,sid);stage.classList.add('fade');sub.classList.add('fade');await wait(3000,sid);guard(sid);stage.classList.remove('fade');sub.classList.remove('fade');document.body.classList.add('minimal');view('<p class="tiny">人生指导系统：运行中</p>');await wait(3000,sid);guard(sid);document.body.classList.add('black');await finish(entry,sid);}
async function finish(id,sid){ending=id;keys();await wait(C.resetTimeout,sid);guard(sid);reset(false);}
function launch(fn){fn().catch(e=>{if(e.message!=='reset'){console.error(e);sub.textContent='运行异常，请按 F1 复位。';}});}
async function runFrom(id,sid){guard(sid);const main=['P1','P2','P3','P4','P5','P6','P7','P8'];const i=main.indexOf(id);if(i>=0){if(i<=0){await sceneP1(sid);guard(sid);}if(i<=1){await sceneP2(sid);guard(sid);}if(i<=2){await sceneP3(sid);guard(sid);}if(i<=3){await sceneP4(sid);guard(sid);}if(i<=4){await question(0,sid);guard(sid);}if(i<=5){await question(1,sid);guard(sid);}if(i<=6){await question(2,sid);guard(sid);}if(i<=7)await sceneP8(sid);return;}
 if(id==='P9C')return passed(sid);if(id==='P9R')return rejected(sid);if(id==='P10B')return contract(sid);if(id==='P11.A1')return endingA('A1',sid);if(id==='P11.A2')return endingA('A2',sid);if(id==='P11.A3')return endingA('A3',sid);if(id==='B')return endingBCore(sid);if(id==='C')return endingC(sid);throw new Error('unknown beat '+id);}
function applyBeatPhase(id){if(id==='P0'||id==='P12'){phase='P0';currentBeat=id;return;}if(id.startsWith('P11')){phase='P11';currentBeat=id;return;}phase=id;currentBeat=id;}
function enterBeat(id,preset){const beat=(window.GAME_BEATS||[]).find(b=>b.id===id);if(!beat){console.warn('unknown beat',id);return;}run?.abort();const sid=++session;run=new AbortController();const state=Object.assign({},beat.state,preset);answers=Array.isArray(state.answers)?state.answers.slice():[];ending=state.ending==null?null:state.ending;hooks=state.hooks||0;hesitate=!!state.hesitate;startKey=state.startKey||'third';clearChrome();applyBeatPhase(id);if(id==='P0'){showStandby();return;}if(id==='P12'){showStandby();if(C.assets.voice['p12.reset'])launch(()=>audio(C.assets.voice['p12.reset'],1500,sid));return;}launch(()=>runFrom(id,sid));}
function reset(operator=false){enterBeat(operator?'P12':'P0');}
window.enterBeat=enterBeat;
window.setDevMuted=on=>{devMuted=!!on;};
window.addEventListener('keydown',e=>{if(typeof window.__devKey==='function'&&window.__devKey(e))return;if(e.code==='F1'){e.preventDefault();if(!e.repeat)reset(true);return;}if(e.repeat||e.metaKey||e.ctrlKey||e.altKey)return;const key=GameRules.key(e.code);if(!key)return;e.preventDefault();if(phase==='P0')enterBeat('P1',{startKey:key});else accept?.(key);});
window.gameStatus=()=>({phase,answers:[...answers],ending,waiting:!!accept,hooks,beat:currentBeat});
window.__devKnownBeats=KNOWN_BEATS;
reset();
